version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
dependencies:
  pre:
    - sudo apt-get update
    - sudo apt-get install -y libgdal-dev
    - sudo apt-get install -y postgis
    - sudo apt-get install -y postgresql-client
    - sudo apt-get install -y python-virtualenv
    - python -m venv venv
echo "hello circle"
